import fs from "node:fs";
const m = JSON.parse(fs.readFileSync("src/generated/metrics.json","utf8"));
console.log("schema_version", m.schema_version);
console.log("top keys:", Object.keys(m).join(", "));
const brief = (k) => { const s = JSON.stringify(m[k]); console.log(`\n== ${k} (${s.length}b) ==\n`, s.slice(0,600)); };
for (const k of ["tickets","workers","spend","browserRuns","quickRuns","memory","routines","logs","daemon"]) brief(k);
console.log("\n== recentActivity len", m.recentActivity.length, "first3 ==");
console.log(JSON.stringify(m.recentActivity.slice(0,3),null,1));
console.log("\n== memory nodes/edges ==", m.memory.nodeCount, "nodes", m.memory.edgeCount, "edges", m.memory.orphanCount, "orphans");
console.log("node sample", JSON.stringify(m.memory.nodes.slice(0,3)));
console.log("edge sample", JSON.stringify(m.memory.edges.slice(0,3)));
